# Generated by Django 6.0.6 on 2026-06-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('gudang', 'Gudang'), ('grosir', 'Grosir'), ('retail', 'Retail')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1433)),
                ('db_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('is_active', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('full_sync', 'Full Sync'), ('auto_sync', 'Auto Sync'), ('monthly_check', 'Monthly Check'), ('yearly_check', 'Yearly Check'), ('full_check', 'Full Check'), ('price_sync', 'Price Sync')], max_length=30)),
                ('status', models.CharField(choices=[('running', 'Berjalan'), ('success', 'Sukses'), ('failed', 'Gagal'), ('partial', 'Sebagian')], default='running', max_length=20)),
                ('tabel', models.CharField(blank=True, max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('total_data', models.BigIntegerField(default=0)),
                ('data_baru', models.IntegerField(default=0)),
                ('data_diupdate', models.IntegerField(default=0)),
                ('data_error', models.IntegerField(default=0)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('pesan_error', models.TextField(blank=True)),
                ('mulai_pada', models.DateTimeField(auto_now_add=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.serverconfig')),
            ],
            options={
                'ordering': ['-mulai_pada'],
            },
        ),
    ]
