# Generated by Django 6.0.6 on 2026-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
