# Generated by Django 6.0.6 on 2026-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutasistokdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pegawaigantishiftdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pegawailemburdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pemakaianbarangdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pembelianorderdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pembelianreturdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='penjualandetailpegawai',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='penjualanjasadetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='penjualanorderdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='transaksibarangdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutasistokdetail',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pegawaigantishiftdetail',
            name='no_transaksi',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='pegawailemburdetail',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pemakaianbarangdetail',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pembelianorderdetail',
            name='kd_barang',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pembelianreturdetail',
            name='no_retur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penjualandetailpegawai',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penjualanjasadetail',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penjualanorderdetail',
            name='no_order',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksibarangdetail',
            name='no_transaksi',
            field=models.CharField(max_length=20),
        ),
    ]
