# Generated by Django 6.0.6 on 2026-06-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('_sync_created', models.DateTimeField(auto_now_add=True, db_column='_sync_created')),
                ('_sync_updated', models.DateTimeField(auto_now=True, db_column='_sync_updated')),
                ('_sync_checksum', models.CharField(blank=True, db_column='_sync_checksum', max_length=64)),
                ('kd_kategori', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=1)),
                ('_sync_server', models.ForeignKey(db_column='_sync_server_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.serverconfig')),
            ],
            options={
                'db_table': 'master_kategori',
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('_sync_created', models.DateTimeField(auto_now_add=True, db_column='_sync_created')),
                ('_sync_updated', models.DateTimeField(auto_now=True, db_column='_sync_updated')),
                ('_sync_checksum', models.CharField(blank=True, db_column='_sync_checksum', max_length=64)),
                ('kd_barang', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kd_kategori', models.CharField(blank=True, max_length=6)),
                ('kd_jenis_bahan', models.CharField(blank=True, max_length=6)),
                ('kd_model', models.CharField(blank=True, max_length=6)),
                ('kd_merk', models.CharField(blank=True, max_length=6)),
                ('kd_warna', models.CharField(blank=True, max_length=6)),
                ('ukuran', models.FloatField(blank=True, null=True)),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=1)),
                ('status_pinjam', models.CharField(blank=True, max_length=1)),
                ('pabrik', models.CharField(blank=True, max_length=1)),
                ('tanggal_daftar', models.DateTimeField(blank=True, null=True)),
                ('_sync_server', models.ForeignKey(db_column='_sync_server_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.serverconfig')),
            ],
            options={
                'db_table': 'master_barang',
                'indexes': [models.Index(fields=['nama'], name='master_bara_nama_033c78_idx'), models.Index(fields=['kd_kategori'], name='master_bara_kd_kate_be214f_idx'), models.Index(fields=['status'], name='master_bara_status_49411a_idx')],
            },
        ),
    ]
